### ISSUE TITLE
[feature request] Default OS and Timeout

### ISSUE THREAD

**Issue by mhtrinh** [raspberrypi/noobs#168]
I would like to suggest those feature for NOOBS: 
- set a default OS to boot (and still keep the feature boot to OS from last time)
- set timeout for default OS

**Comment by Ruffio** [comment]
@mhtrinh is this still an issue?

**Comment by mhtrinh** [comment]
Because NOOBS lack this feature, I end up using another way to do it. If some day this feature end up in Noobs, then I will probably use it. 
But it seems I'm the only one who need this ...

**Comment by robgjansen** [comment]
I would very much like the ability to make the default OS sticky, rather than always automatically updating the default OS to the last-selected OS. I like the option suggested here:

    default_partition_to_boot=last # boot to last selected OS
    default_partition_to_boot=5 # boot to partition 5, no matter the last selected OS

The use case is when the user is dual-booting where one installed OS does not require a graphical interface (e.g., raspbian lite, and/or pidora configured with runlevel 3) and one installed OS does require a graphical interface (e.g., OpenELEC, and/or RetroPie).

When the non-graphical OS is the main OS and primarily accessed through a serial cable, it gets very annoying to boot back into that after, e.g., connecting to the TV to play a game in RetroPie. Currently, the user would need to boot back into raspbian from the TV to make sure the default is updated before going back to the serial cable method, or otherwise figure out how to get to the correct partition to update the setting manually.

Concerning the issue raised about booting into a non-existent partition: I believe that is a rare condition and should be testable programmatically. If the default partition doesn't exit, we can go back to the "last" setting again.

**Comment by robgjansen** [comment]
One way to implement this:

`default_partition_to_boot=5` would boot partition 5, and auto-update the setting to the last-selected OS (current behavior), and then `default_partition_to_boot=-5` would also boot partition 5, but there would be no auto-update of the setting.

To handle the "partition does not exist problem", in that case we can boot into recovery, since that is always in partition 1.

**Comment by procount** [comment]
I have implemented my take on this requirement in PINN.
Please look in https://sourceforge.net/projects/pinn/files/testing/ and use pinn-212a.zip in the same way as noobs-lite.
By adding 'bootmenutimeout=X' to recovery.cmdline you can change the OS boot selection menu timeout to X seconds.
The boot selection dialog now has a checkbox next to each installed OS. Only one can be checked at a time. The checked OS becomes the default sticky OS that is booted on each boot with no intervention, regardless of the last OS chosen. When a 'sticky' OS is set, then the menu timeout will drop to 1 second, giving just enough time to hit a key to choose another OS to be booted on the next boot only. 
It's not quite as I want it yet, but I just wanted to throw this proof of concept out there to see what people thought about it.

**Comment by procount** [comment]
On https://sourceforge.net/projects/pinn/files/testing/ I have deleted pinn-212a.zip and replaced it with pinn-212b.zip which works much better.
Here are the new features:
1. By adding 'bootmenutimeout=X' to recovery.cmdline you can change the OS boot selection menu timeout to X seconds.
2. On the OS Boot Selection dialog, ONE of the installed OSes may be checked to make it a sticky default OS. On subsequent boots, this is the OS that will be booted automatically without delay, if the user does not interact with the system. The user may still hold shift, press the Left mouse key, CEC remote key, or touch the touchscreen to enter the main dialog menu. Exiting from here will still go to the boot selection dialog to choose another OS to boot or change the default OS. An OS chosen here will boot once, but if a default OS is set, that will be used on following boots.
3. If no sticky flags are set, the boot sequence operates as before, except bootmenutimeout is used for the timeout.
4. The title bar indicates PINN.
5. A left mouse click will now also halt the boot and enter the main dialog (just like the shift key).

Comments welcome. I should be able to adapt this to NOOBS as well and create a PR if there is enough interest.

**Comment by procount** [comment]
These features are now released in PINN p2.1.2

**Comment by XECDesign** [comment]
No plans to add this to NOOBS.

**Comment by korokinopio** [comment]
One other reason for the boot menu time out option is for people who don't have the dexterity to select the OS they want in the 10 time limit.
I'll use an example from my own life.
I just set my elderly father up with a RPi to act as a media box.
It currently has raspbian and libreelec installed on it
Because it's a media box, it's hidden behind his TV
The has a wireless air mouse connected to it
At his age, the 10 seconds is just about not enough for him to select the different OS

I wouldn't necessarily need the default OS settings, except that he would be running it most often in libreelec, so cutting the number of times he has to select an OS down by half might not be a bad thing

**Comment by procount** [comment]
In NOOBS you have the `forcetrigger` option which will provide indefinite time but it needs more mouse clicks even in the default case.

If you need the adjustable menu timeout, try PINN, which has that plus a lot more options, but is otherwise compatible with NOOBS and will look familiar.

**Comment by biswaKL** [comment]
> In NOOBS you have the `forcetrigger` option which will provide indefinite time but it needs more mouse clicks even in the default case.
> 
> If you need the adjustable menu timeout, try PINN, which has that plus a lot more options, but is otherwise compatible with NOOBS and will look familiar.

Thanks @procount , its working like a charm.
One thing to notice that it will only trigger if the os release date is greater than os installed date.

**Comment by procount** [comment]
What is working like a charm - forcetrigger or PINN?

Forcetrigger will ALWAYS force the recovery menu to be shown regardless of any dates.
