### ISSUE TITLE
Can't install raspbian at some "4GB" SD Cards

### ISSUE THREAD

**Issue by xfalcox** [raspberrypi/noobs#176]
Hey,

I think we can put a tip at https://github.com/raspberrypi/noobs/blame/master/README.md#L32
saying that you need to delete some contents at the default image to install raspbian at some "4GB" Cards?

**Comment by Max-Headroom** [comment]
Just spend the past two hours trying to figure out why I can't find the other OS's as shown on the many blogs and write-ups on getting started and installing NOOBS. So now they are ALL outdated as well. Even the Raspberry Pi User Guide, third edition, by Eben Upton, is now also wrong.
No where on the front end pages such as main http://www.raspberrypi.org/downloads/ is it said that the OS's has been limited down to just 1 now.
And searching deeper in some forums, etc. It looks to me very few people are pleased.
I agree with kaamil1984. This is a major change. To say "Can't please all the people all the time..." sounds like a cop out.
I think if you really want to go this route, then you should have 3 versions: lite, medium(this) and full. And make it clear on the official documentation.

**Comment by kaamil1984** [comment]
Welcome to Linux world, where most developers have no idea about project and product management.

**Comment by ghollingworth** [comment]
The reason we were having trouble with the larger NOOBS was because it wouldn't fit onto a 4G card and it was becoming a support and testing burden.  (It was taking up to a week longer to release a version because of the multiple releases that need to be tested before committing to pre-imaged SD cards)

Until something changes (i.e. we have a better mechanism of testing the configurations) we are not going to add them back.

Gordon

**Comment by navigat0** [comment]
I understand both sides of this picture and it seems to me NOOBS is oriented towards beginners - riiiight?  So if the number of OS choices is becoming unmanageable, at the very least it would be advisable to write up a HOW TO: for the network install instructions to install all compatible and/or  recently removed) OS choices.  I also feel that stripping down to a single OS kind of defeats a core feature of NOOBS which is the OS selection tool (which ironically will only list OSes installed with NOOBS).

**Comment by Ecordonnier** [comment]
Using Noobs 1.9.2, I was unable to install Raspbian on a 4GB SD card because the partition was too small. Actually this page (https://www.raspberrypi.org/learning/software-guide/) correctly states that a 8 GB SD card is required.

**Comment by Arblabla** [comment]
it's very nice that this info is written on some place i never heard of, at least its somewhere. like max h. i just wasted the past two hours following the most current instructions i could find, in fact i used others that said the same things, trying to t/s what i was doing wrong, and then find that the mfg's 4gb image doesn't work on a name brand standard 4gb card, maybe a hint on what to do about it would be helpful- i mean a hint that is somewhere i'm likely to be (the download page?). The other option is i just reconfigured more than anyone wants to know to get the other system up. But i don't know, maybe it's not their problem and a problem with the standard name brand sdcard. But then, i'm a complainer..

This is a quote from the 2.1.0 version readme file:

NOOBS INSTALLATION INSTRUCTIONS

1. Insert an SD card that is 4GB or greater in size into your computer.

On the one hand, i'm an idiot as well as a complainer- there isn't 4gb of space left to install to. I just assumed it would have an option to install to whatever card you put in a usb stick on usb port because i'm a beginner. On the other, i should do what most others do, instead of complain, look at some of the alternatives instead of raspb.. It seems like a really nice mini computer tho.

**Comment by Arblabla** [comment]
I'd also like to take this special moment to say, i just spent a lot of time reconfig'ing the other system since pi is now offline so that i could come here to complain (i'm a complainer), and now i just realized that this system will send god knows what to your email unless you remember that everyone wants to opt you into email lists unless you waste more time wading thru yet another kind of menu to figure out where their options are, you know, the checkbox that says "don't bug me about stupid things", though roughly half of them seem to either send stuff to you or send your info to 3rd parties.

**Comment by Arblabla** [comment]
it's very nice that this info is written on some place i never heard of, at least its somewhere. like max h. i just wasted the past two hours following the most current instructions i could find, in fact i used others that said the same things, trying to t/s what i was doing wrong, and then find that the mfg's 4gb image doesn't work on a name brand standard 4gb card, maybe a hint on what to do about it would be helpful- i mean a hint that is somewhere i'm likely to be (the download page?). 

This is a quote from the 2.1.0 version readme file:

NOOBS INSTALLATION INSTRUCTIONS

Insert an SD card that is 4GB or greater in size into your computer.

On the one hand, i'm an idiot as well as a complainer- there isn't 4gb of space left to install to. I just assumed it would have an option to install to whatever card you put in a usb stick on usb port because i'm a beginner, as far as rasp's go.

**Comment by lurch** [comment]
Yeah, the growing size of the Raspbian image means that NOOBS no longer fits on 4GB cards.
Re-opening this issue as the instructions (in various places) should be updated to say 8GB instead.

**Comment by XECDesign** [comment]
A little tricky, since NOOBS itself does not need an 8GB card and most of the options will install just fine on a 4GB card. There is nothing Raspbian-specific in those instructions, but it would make sense to mention that some operating systems may need more space to install.

**Comment by XECDesign** [comment]
Yeah, it's probably best not to be pedantic and just say 8GB everywhere rather than get into the caveats.

**Comment by XECDesign** [comment]
Should be updated now.
