### ISSUE TITLE
Re-install a distro without wiping other distros

### ISSUE THREAD

**Issue by dem1980** [raspberrypi/noobs#193]
When we install or reinstall a distro in the sd card using NOOBS, the distros that are already on the sd card are erased/reseted.
It could be nice to add a distro without deleting all files and config we made in others distros.

**Comment by Ruffio** [comment]
@dem1980 is this still an issue?

**Comment by narspt** [comment]
+1, it would be a great feature! just an extra button for "Reinstall" (or right click on OS context option?) that would simply reinstall the selected OS, without touching partitions, just cleaning that single OS partition and reinstall/refresh it (guess it would be as simple as clean partitions and uncompress fresh OS files again)

lurch mentions about possible different partition size requirements for more recent OS version... well you could just add code to check if it's possible to reinstall on the existing partition size(s)... if not possible then just tell the user that unfortunately it's not possible due to new requirements for that OS... but I guess it would still be usable most of times.

**Comment by procount** [comment]
Implemented in  [PINN v2.4.5e](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574&start=250#p1265950)

**Comment by XECDesign** [comment]
No plans to add this to NOOBS.
