### ISSUE TITLE
Mouse Oddity

### ISSUE THREAD

**Issue by AndrewdAzotus** [raspberrypi/noobs#228]
I have an interesting problem. I have two SD cards, the older image with the menu button at the bottom and everything works fine. The second image with the menu button at the top and the mouse does not work within x and dmesg shows the mouse disconnecting every minute or so. Everything is the same except for the SD card image.

has anyone else encountered this problem?

**Comment by lurch** [comment]
From your description of "menu button at the bottom / top", I assume you're talking about [Raspbian](http://www.raspberrypi.org/changes-to-the-raspbian-user-interface/) rather than NOOBS? The menu buttons in [NOOBS](https://github.com/raspberrypi/noobs#os-installation) have never moved ;-) 
NOOBS is merely an OS installer that makes installing Raspbian much easier.

It sounds like your problem may be kernel-related (older versions of Raspbian were using a 3.12.y kernel, the latest version of Raspbian (released on 31st Jan) now uses a 3.18.y kernel), so try creating an issue against the [kernel](https://github.com/raspberrypi/linux/issues).

Closing as invalid, as this isn't a bug in NOOBS itself. Just out of interest, if you tap on the shift-key at power-on to force the NOOBS GUI to appear, does the mouse work in there?
