### ISSUE TITLE
Cannot load kernel modules in rescueshell

### ISSUE THREAD

**Issue by HanSooloo** [raspberrypi/noobs#272]
**Steps to reproduce:**
1. `git clone https://github.com/raspberrypi/noobs.git`
2. `cd noobs/buildroot`
3. `make linux-menuconfig KCONFIG_CONFIG=kernelconfig-recovery.armv7`
4. `make linux-savedefconfig`
5. `cd ..`
6. `./BUILDME.sh`
7. Copy noobs/output to SD card recovery partition
8. Mount /dev/mmcblk0p1 on /mnt/p1
9. Add 'rescueshell' to /mnt/p1/recovery.cmdline
10. Reboot
11. At Safe Mode rescueshell, `lsmod`

**Observed results:**
```
/ # lsmod
lsmod: /proc/modules: No such file or directory
Modules                         Size    Used by      Not tainted
/ # ls /lib/modules
ls: /lib/modules: No such file or directory
/ #
```

**Expected results:**
1. lsmod shows the table, but without any modules (not sure if this should work)
2. /lib/modules should contain the modules that were configured in `make linux-menuconfig KCONFIG_CONFIG=kernelconfig-recovery.armv7`

**Comment by lurch** [comment]
This is expected behaviour. The NOOBS kernels are configured without loadable module support.
If there are any extra kernel modules you need in your custom-built NOOBS kernel, you'll have to build them directly into the kernel. Just out of curiosity, what do you need to add?

And rather than passing the KCONFIG_CONFIG option to make, you can simply run `./make_arch_linux-menuconfig.sh armv7` from the base `noobs` directory.
