### ISSUE TITLE
Language native name not showed right

### ISSUE THREAD

**Issue by bovirus** [raspberrypi/noobs#374]
In file

\recovery\languagedialog.cpp

There is this code to read and show language name in native language

        QString langcode = langfile.mid(12);
        langcode.chop(3);
        QLocale loc(langcode);
        /* Display languagename in English, e.g. German, French */
        /* QString languagename = QLocale::languageToString(loc.language()); */
        /* should Display languagename in native language, e.g. Deutsch, Français  */
        QString languagename = loc.nativeLanguageName();
        QString iconfilename = ":/icons/"+langcode+".png";

I have a problem with 

Spanish (file language_es.ts) - code=es
Asturian (file language_es-XA.ts) - code=es-XA

Language name showed for both "Espanol de espana". Is it right?

I propose to enlarge the width of drop down list for language (the european portoguese native name is truncated on the right).
In the UI there is a lot of space unused and you can enlarge the width of language name list.

**Comment by procount** [comment]
QT only seems to support 2 character country codes from ISO 639-1.  How should we support longer country codes and what format should they use?

Chinese (Taiwan) is already indicated as 'zh_TW', so is this the correct format?

Asturian could be: 'es_XA', 'es-XA' or 'ast'. But using 'es_XA' results in a native language name of "espagnol de Espana", which is the same as Spanish and probably not correct. Is that because it just uses the first 2 letters of the country code? And does that mean 'zh_TW' is simply being displayed as 'Chinese'?

Basque could be 'eu' or use it's subdivisions of 'eu_ES' or 'eu_FR'.

Probably the best way is to detect the longer country codes and provide a separate set of language names for them in a separate translatable language file that translators can edit to augment QT, but what is the correct language code format to use for these?

**Comment by bovirus** [comment]
@procount 
I believ that is more simple to add a string value (ex. NativeLanguagename) in .TS language file and use tio show the native language name.

Bsque = eu
Asturian = es_XA

**Comment by XECDesign** [comment]
Fixed by https://github.com/raspberrypi/noobs/commit/5136f34c9aa0a2550b89eb17bc07aaad1d1fbf3b
