### ISSUE TITLE
UBOOT images

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#511]
(A question for the gurus, rather than an issue)

There have been several requests to add images to NOOBS/PINN that are based on U-boot, including the BSD range of OSes and some AARCH64 images. None have been successful. 

Having laboured to convert yet another image and failed, I have come to the conclusion that it is a futile exercise, since I read somewhere that UBoot only looks at the first partition of a disk for its initial files, like: boot.scr or the next kernel image. 

I found one attempt to make UBoot multi-boot, but it still required all uboot files to be on partition 1, so only the rootfs were on separate partitions. This does not really fit with the NOOBS architecture.

But it seems to me that Uboot is largely superfluous here, as many OSes boot without it (incl. the 64-bit Gentoo version) and can be loaded by the normal VC boot loader (?). So, I'm thinking that it should be possible to remove UBoot from such OSes altogether and just boot them normally.

I'm sure I read of a way to do this somewhere, but my google fu is failing me. So my questions are: 

- Is this a feasible way forward?
- Can all UBoot based images be converted?
- Is there a standard technique to convert such OSes?

**Comment by XECDesign** [comment]
I think that's a question best asked of the maintainers of those distros. Why have they made the choice to add uboot in the first place?

If you wanted to look into it on your own, you could check their kernel updating mechanism. Do they add grub of a UEFI implementation after uboot?

**Comment by procount** [comment]
Well, blow me down! I just managed to remove uboot from Emteria!
Now, I wonder if I can relocate it to a logical partition a lá NOOBS and get it to still boot.......

**Comment by procount** [comment]
UPDATE: Emteria is now installed and booting from PINN! 😃 
Recovery mode doesn't work (as I expected), but it's a start.

**Comment by lurch** [comment]
IIRC (but I might be mis-remembering) @resin-io use uboot for their RPi images, as they need to explicitly switch the rootfs partition for atomic updates, and they're using uboot rather than "NOOBS mode" as this gives them consistency with all the other platforms that they support https://resinos.io/#downloads

**Comment by procount** [comment]
That makes sense. It looks like Emteria switches between ramdisk.uimg and recovery.uimg (so switching ramfs rather than rootfs) but does it from within Android. So I think they might need to make a small mod for it to work without UBoot.

**Comment by maxnet** [comment]
>Why have they made the choice to add uboot in the first place?

Probably because that is what the rest of the ARM board world uses.
So if you would like to give users the freedom to run your distribution on multiple boards, using uboot pretty much make sense.


A problem I ran into when producing a single image that is meant to run on multiple boards, is that kernel and ramdisk files that are generated for use with uboot (uimage/uinitrd) tend to have extra header and checksum information on them.

If you want a single ramdisk file that can be used with multiple boards, that can be a problem.
If you let the Raspberry Pi firmware serve the uinitrd file to Linux, the firmware will not understand the extra header, will not strip it off the file, pass it as-is to Linux, and Linux will choke on it.
Can be worked around by having a separate ramdisk file for the Pi firmware, putting uboot in between, or [patching](https://github.com/maxnet/berryboot/blob/berryboot2015/buildroot-2015.02/kernel-patches/uinitrd.patch) kernel to skip the header information the firmware does not strip.

**Comment by procount** [comment]
Just skipping the header is not sufficient to get a uboot ramdisk working with NOOBS. Often that image is where fstab is stored and it obviously needs to be patched for NOOBS. So it may as well be stripped off at the same time, although it makes for an interesting partition_setup.sh file!

**Comment by XECDesign** [comment]
and they just use mmcblk0 in their fstab files?

**Comment by maxnet** [comment]
>Often that image is where fstab is stored and it obviously needs to be patched for NOOBS.

Then that distribution has bigger problems.

Often location of rootfs is passed through kernel command line parameters.
Which when using uboot is typically in uEnv.txt or similar.

**Comment by procount** [comment]
And yet others are in boot.scr.uimg (with another header).
Flexibility leads to inconsistency.

**Comment by procount** [comment]
> and they just use mmcblk0 in their fstab files?

Generally yes, but Android is a bit odd. An excerpt (off the top of my head) from one of their fstab is as follows:
```
/dev/block/mmcblk0p1  /boot ....
/dev/block/mmcblk0p2  /system ....
/dev/block/mmcblk0p3  /oem ....
/dev/block/mmcblk0p4  /data ....
```

**Comment by lurch** [comment]
> And yet others are in boot.scr.uimg (with another header).
Flexibility leads to inconsistency.

https://xkcd.com/927/ :rofl:

**Comment by procount** [comment]
Closing discussion
