### ISSUE TITLE
Supported USB WiFi devices for Recovery Mode

### ISSUE THREAD

**Issue by allenhuffman** [raspberrypi/noobs#542]
The README mentions the official Pi USB WiFi module, but that was apparently discontinued in 2018. What are the requirements for a USB WiFi module for Recovery Mode?

**Comment by XECDesign** [comment]
I don't know if there are any usb devices currently sold which use a supported chipset.

Devices which use the brcmfmac driver should be covered. That includes the on-board wifi of pis which have it.

**Comment by lurch** [comment]
@procount Did you add support for a wider range of WiFi dongles to PINN ?

**Comment by procount** [comment]
Yes, but I had to drop a lot of Realtek drivers because of the maintenance of having to resolve name-clashes (They all use the same driver source code). I will probably put them back in when I support modular drivers.

But I have already answered Allen on the Forum: https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=239630 . He has a Ralink RT5370 which is supported by PINN.
