### ISSUE TITLE
noobs/pinn translation language alignment

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#570]
I was asked about such alignment. see https://github.com/procount/pinn/issues/352
I think the 'ar' code in NOOBS should be 'ae'.

**Comment by lurch** [comment]
https://github.com/raspberrypi/noobs/pull/568#issuecomment-582983628 :wink: 

It gets kinds confusing because to do internationalisation & localisation "properly" you need separate settings for Language, Country and Keyboard settings (and then you also have dialects like pt_BR for Brazilian Portuguese).
But (to try and keep things simple) NOOBS conflates all of these into a single setting.

**Comment by procount** [comment]
So maybe 'ar' is correct, then.
OK. I'll look to revert changes in PINN then. I think it's largely an internal issue anyway.
