### ISSUE TITLE
First primary partition FAT16?

### ISSUE THREAD

**Issue by andrew-rogers** [raspberrypi/noobs#598]
https://github.com/raspberrypi/noobs/blob/134417fba944a44c3a1b1de42c290d8bdfd0c6f5/recovery/initdrivethread.cpp#L258

The SD cards are normally formatted to FAT32 and contain a FAT32 filesystem on the first primary partition. I notice the code '0E' is used instead of '0C' when the recovery program re-partitions the drive. Is this intentional? If so, is the filesystem converted to FAT16 later on?

**Comment by lurch** [comment]
> If so, is the filesystem converted to FAT16 later on?

Nope. Looking at the rest of the function you linked to, it looks like it resizes the first primary partition, and then uses `sfdisk` to write out a new partition table with the first partition, the extended partition and the settings partition. So I guess you _could_ argue that the function should read the existing partition-id for the first partition and write that back, rather than always overwriting the first partition's id with `0E`; but I suspect in practical terms it makes no actual difference, i.e. it doesn't really matter if the partition-id exactly matches the filesystem type, as long as they're both some flavour of FAT.
(if it did cause problems, I'm sure we'd have heard about it by now :wink: )
